name: newsify
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.8
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.1.0
  firebase_core: ^1.12.0
  firebase_database: ^9.0.6
  flutter:
    sdk: flutter
  flutter_tts: ^3.3.3
  share_plus: ^4.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
